### ISSUE TITLE
System hardware configuration suggested for the pipeline?

### ISSUE THREAD

**Issue by NitaAgarwal2022** [healthylaife/MIMIC-IV-Data-Pipeline#34]
Hi,

Thank you all for creating this useful and flexible pipeline.

Can you please suggest the System hardware configuration suggested for the pipeline and what will be the time taken to pre-process the data for version1. Thanks!

**Comment by mehak25** [comment]
Thanks for checking out our work and providing your feedback.
The timings to run each step depend on the cohort you are selecting and how many features you are including in the cohort. In general, it should not take more than a few hours (2 to 4 hours) to run any step. For smaller cohorts it may take only few minutes for each step.
Time for deep learning model training depends on system configuration. A GPU system will train the models much faster than a CPU system.

Below are the hardware and software requirements:

Hardware:
Operating system: Windows 10+ or above/ MacOS 11+
To run the model training using this pipeline you will need GPU configuration similar to NIVIDIA GeForce RTX (8 GB)

Software: Pyhton: 3.7

import_ipynb==0.1.3
ipywidgets==7.5.1
Jinja2==2.11.2
matplotlib==3.2.2
numpy==1.18.5
pandas==1.0.5
scikit_learn==1.0.2
torch==1.6.0
tqdm==4.47.0

Please let us know if you need any more information.

Thanks.

**Comment by NitaAgarwal2022** [comment]
Great! This is really helpful.
