### ISSUE TITLE
No license is declared

### ISSUE THREAD

**Issue by SphtKr** [healthylaife/MIMIC-IV-Data-Pipeline#35]
Could you please declare a license in your repo? Without a `LICENSE` file or declaration of the license terms in the `README.md`, [the code is technically "all rights reserved"](https://choosealicense.com/no-permission/) by the authors and reuse of the code is limited. If you are unopinionated on the matter, I suggest the [MIT license](https://choosealicense.com/licenses/mit/) as it is highly compatible--particularly with university IP licenses ([such as this one](https://github.com/sunlabuiuc/PyHealth/blob/master/License.txt)).

If an MIT license is acceptable I'd be happy to submit a PR to include it.

Thanks!

**Comment by mehak25** [comment]
We have added MIT License to the repo. Thanks for your feedback.
