### ISSUE TITLE
How to get exact item code for specific disease

### ISSUE THREAD

**Issue by yirufang2001** [healthylaife/MIMIC-IV-Data-Pipeline#38]
I found in your project for specific diseases you let the icd_code to have different value (like for CKD, the icd_code is N18), I just wonder do you offer exact item ids for the specific disease? Where can I find them?  Or can you tell me how do you define the kidney disease? Thanks.

**Comment by mehak25** [comment]
Our strategy for extracting disease-specific cohorts is as follows:

1. We first convert all ICD9 to ICD10 codes present in diagnoses_icd.csv file.
2. We use file in utils/mappings/ICD9_to_ICD10_mapping.txt to convert ICD9 to ICD10.
3. We then identify the disease label with the first three letters of icd10 codes. For CKD the root is N18.
4. You can use preprocessing/day_intervals_preproc/disease_cohort.py to see what codes come under every root node.
5. For N18, the ICD 10 codes are N181, N182, N183, N184, N185, N186, N189.

Thanks.
