### ISSUE TITLE
Issue of prediction window

### ISSUE THREAD

**Issue by janine112** [healthylaife/MIMIC-IV-Data-Pipeline#39]
Hi there,

Thanks for the amazing work!

When selecting the prediction window using the jupyter notebook (mainPipeline.ipynb), it seems that the corresponding code should be:
 `if (radio_input6.value=='Custom'):
    predW=int(text3.value)
else:
    predW=int(radio_input6.value[0].strip())`
 
for 'section 7. Time-Series Representation', cell 2. The current code seems to mix up the inputs of the prediction window and the bucket.

Best wishes

**Comment by mehak25** [comment]
Thanks for your valuable feedback. The issue is resolved.
